### ISSUE TITLE
403 Forbidden After Instal Wordpress on Fresh New Installation

### ISSUE THREAD

**Issue by ahmadrusli** [litespeedtech/cyberpanel#1072]
Hi all..

I just install fresh new installation cp on digitalocean.
Tried enterprise version.
After create new website, it is ok.
After install wordpress, then 403 forbidden appears.

Thank you

![Untitled-1](https://github.com/usmannasir/cyberpanel/assets/1385052/31deef0a-4a4b-483d-82fd-7b2964f82d21)

![Untitled-2](https://github.com/usmannasir/cyberpanel/assets/1385052/7afbe986-7d80-478d-8827-841506f7fcd0)

![Untitled-3](https://github.com/usmannasir/cyberpanel/assets/1385052/bc219b64-96ca-40e4-ae3a-c943dc413952)

![Untitled-4](https://github.com/usmannasir/cyberpanel/assets/1385052/89978ce5-cacb-4460-b1b6-e61b690ebc3d)

**Comment by packetdog** [comment]
Please try to Open the File Manager for the site, and click on Fix Permissions at the top right side.

What methodology did you use to install Wordpress?

**Comment by ahmadrusli** [comment]
> Please try to Open the File Manager for the site, and click on Fix Permissions at the top right side.
> 
> What methodology did you use to install Wordpress?

Thank you. I just tried, and still not fixed.
I use click "WP + LSCache" method.

I tried twice. i delete that website.
then create new website again.
this step, web works well no problem.
but, after instal wordpress, then 403 forbidden.

**Comment by ahmadrusli** [comment]
There are so many error logs messages.

![Untitled-5](https://github.com/usmannasir/cyberpanel/assets/1385052/468008ed-cd9a-4655-9c44-9ef08e3ea730)

**Comment by ahmadrusli** [comment]
But i can access file manager. it looks it installed well.
But server having problem access PHP?
I do know how to solve it.

![Untitled-6](https://github.com/usmannasir/cyberpanel/assets/1385052/bb85cd6d-8e04-46e1-9af2-00ff6fe5d364)

**Comment by packetdog** [comment]
Go to Websites > List Websites, then find your site, and click to Manage it. Inside this area, please click on Change PHP, and select the highest version possible. I'm not sure if php7.4 isn't installed on your server, or if it's something else. Very odd on a fresh install it wouldn't work out of the box.

What server OS and version are you running it on?

**Comment by ahmadrusli** [comment]
Thank you. Yes. a little bit odd. i hope after i install wordpress, i can work. but this is happened. 

It is Ubuntu 23.04 comes directly from digitalocean marketplace.

I will try to recreate website but using openlitespeed, not enterprise. want to see if the problem comes in enterprise only or both version.

**Comment by ahmadrusli** [comment]
I just try destroy the droplet.
and try again until install wordpress.
the website running good no problem.
so for the meantime i will stick with OpenLiteSpeed.

thank you.

**Comment by packetdog** [comment]
> the website running good no problem.

Great! Yes, I installed on my VPS by installing Ubuntu Server, and using CyberPanel script to configure.. so a difference there. I've never tried to use teh VPS pre-built scripts/images. Glad to hear this is resolved. @usmannasir if you don't think this warrants any further investigation you can close this, I don't seem to have access to.

**Comment by ahmadrusli** [comment]
Just installed new server.
And problem still existed.

Steps, not working:
1. Install CyberPanel on new DigitalOcean Droplet.
2. Create new website.
3. Upgrade to LiteSpeed Web Server Enterprise.
4. Install Wordpress. then 403 Forbidden happened.

Works well if:
1. Install CyberPanel on new DigitalOcean Droplet.
2. Create new website.
3. Do not Upgrade to LiteSpeed Web Server. Use only default: OpenLiteSpeed.
4. Install Wordpress. Wordpress will run well, no problem.

**** Wait. Just got solution ****

I change from **PHP 8.1 to 8.0** and now work well.

So, when you want instal new website, for now, **choose PHP 8.0**.

**Comment by jodhpurlaxman** [comment]
This kind of issue occurs when you have selected the php version not installed on server but listed in cyberpanel phpversion. Same happened with me and switching to installed version resolve the issue

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.
