### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vishwanathstudioscontent** [litespeedtech/cyberpanel#1447]
after update to the 2.4.2 to the latest commit today. website are not loading 503 error.

**Comment by vishwanathstudioscontent** [comment]
i have paid all addons pack which enable me to use apache as reverse proxy but after the update the 503 error appeared but when i switched to openlightspeed the issue is gone. do address this. also i don't know weather my paid version is alive or not about all addons pack.

**Comment by usmannasir** [comment]
this is fixed now.

**Comment by vishwanathstudioscontent** [comment]
@usmannasir  I think it is still not resolved i tried swiching back to openlightspeed + apache as reverse proxy and website is showing 503. working fine with pure lightspeed.
