### ISSUE TITLE
[BUG] Design does not apply to root directory.

### ISSUE THREAD

**Issue by Slddev** [litespeedtech/cyberpanel#759]
**Describe the bug**
Design does not apply to root directory only the /base/.

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. Apply a custom CSS.
2. Go to your root directory (cyberpanel.domain.com/)
3. CSS does not apply there. But it does at /base/

**Expected behavior**
Apply CSS on the root directory aswell

**Operating system:**
Ubuntu 20.04.03 LTS

**CyberPanel version:**
2.1.2

**Comment by usmannasir** [comment]
Can you share the design with the community?

**Comment by Slddev** [comment]
Sure! Its all here: https://github.com/Slddev/CyberPanel-Themes

**Comment by Slddev** [comment]
While I'm at it, please add support to override the file manager CSS and the login too (if possible.)

**Comment by usmannasir** [comment]
fixed.

**Comment by Slddev** [comment]
Nope, not fixed yet. It's not about the login page. Login then remove /base/ and just leave it at the root directory. The design will not apply there. @usmannasir
